# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{airbrush}
  s.version = "0.0.5.pre6"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Marcus Crafter", "Nick Marfleet"]
  s.date = %q{2011-06-18}
  s.email = %q{nick@blocksglobal.com}
  s.executables = ["airbrush", "airbrush-example-client"]
  s.extra_rdoc_files = [
    "LICENSE",
     "README.txt"
  ]
  s.files = [
    ".gitignore",
     "History.txt",
     "LICENSE",
     "README.txt",
     "Rakefile",
     "VERSION",
     "bin/airbrush",
     "bin/airbrush-example-client",
     "extras/image_reaper.rb",
     "lib/airbrush.rb",
     "lib/airbrush/client.rb",
     "lib/airbrush/core_ext/get_args.rb",
     "lib/airbrush/core_ext/timestamped_logger.rb",
     "lib/airbrush/handler.rb",
     "lib/airbrush/listeners/listener.rb",
     "lib/airbrush/listeners/memcache.rb",
     "lib/airbrush/listeners/zeromq.rb",
     "lib/airbrush/processors/image/image_processor.rb",
     "lib/airbrush/processors/image/profiles/cmyk-profile.icc",
     "lib/airbrush/processors/image/profiles/srgb-profile.icc",
     "lib/airbrush/processors/image/rmagick.rb",
     "lib/airbrush/processors/processor.rb",
     "lib/airbrush/server.rb",
     "lib/airbrush/version.rb",
     "log/debug.log",
     "script/destroy",
     "script/generate",
     "script/txt2html",
     "spec/airbrush/client_spec.rb",
     "spec/airbrush/core_ext/get_args_spec.rb",
     "spec/airbrush/core_ext/timestamped_logger_spec.rb",
     "spec/airbrush/handler_spec.rb",
     "spec/airbrush/listeners/listener_spec.rb",
     "spec/airbrush/listeners/memcache_spec.rb",
     "spec/airbrush/processors/image/image_processor_spec.rb",
     "spec/airbrush/processors/image/rmagick_spec.rb",
     "spec/airbrush/processors/processor_spec.rb",
     "spec/airbrush/publishers/memcache_spec.rb",
     "spec/airbrush/publishers/publisher_spec.rb",
     "spec/airbrush/server_spec.rb",
     "spec/airbrush_spec.rb",
     "spec/spec.opts",
     "spec/spec_helper.rb",
     "tasks/rspec.rake"
  ]
  s.homepage = %q{http://www.blocksglobal.com}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.4.2}
  s.summary = %q{Gem for providing messaging system for media processing}
  s.test_files = [
    "spec/airbrush/client_spec.rb",
     "spec/airbrush/core_ext/get_args_spec.rb",
     "spec/airbrush/core_ext/timestamped_logger_spec.rb",
     "spec/airbrush/handler_spec.rb",
     "spec/airbrush/listeners/listener_spec.rb",
     "spec/airbrush/listeners/memcache_spec.rb",
     "spec/airbrush/processors/image/image_processor_spec.rb",
     "spec/airbrush/processors/image/rmagick_spec.rb",
     "spec/airbrush/processors/processor_spec.rb",
     "spec/airbrush/publishers/memcache_spec.rb",
     "spec/airbrush/publishers/publisher_spec.rb",
     "spec/airbrush/server_spec.rb",
     "spec/airbrush_spec.rb",
     "spec/spec_helper.rb"
  ]

  s.add_runtime_dependency(%q<activerecord>, ["= 3.0.10"])
  s.add_runtime_dependency(%q<activesupport>, ["= 3.0.10"])
  s.add_runtime_dependency(%q<actionpack>, ["= 3.0.10"])
  s.add_runtime_dependency(%q<hpricot>, [">= 0"])
  s.add_runtime_dependency(%q<curb>, [">= 0"])
  s.add_runtime_dependency(%q<live_ast>)
  s.add_runtime_dependency(%q<starling>)
  s.add_runtime_dependency(%q<rmagick>) 
  s.add_development_dependency(%q<rspec>, [">= 1.2.9"])
end

